name: pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.4.0

      - name: build
        run: |
          npm ci
          npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: pages
          folder: dist
